### ISSUE TITLE
fizzbuzz 구현

### ISSUE THREAD

**Issue by 1daero** [1daero/fizzbuzzforme#1]

**Comment by 1daero** [comment]
## 목표

나 혼자 완성해보는 fizzbuzz

## 요구사항
- 범위: 1~20까지의 정수

## Tasks
- [x] 3의 배수라면 fizz출력
- [x]  아무것도 아니라면 숫자 그대로 출력
- [x]  5의 배수라면 buzz 출력
- [x]  15의 배수라면 fizzbuzz 출력

##Reference
https://en.wikipedia.org/wiki/Fizz_buzz
